development:
    domain:             localhost:3000
    twitter_key:        
    twitter_secret:     
    facebook_key:       
    facebook_secret:    
    linked_in_key:      
    linked_in_secret:   

test:
    domain:             test.host
    twitter_key:        
    twitter_secret:     
    facebook_key:       
    facebook_secret:    
    linked_in_key:      
    linked_in_secret:   

production:
    domain:             example.com
    twitter_key:        
    twitter_secret:     
    facebook_key:       
    facebook_secret:    
    linked_in_key:      
    linked_in_secret: